### ISSUE TITLE
Does not download automatically

### ISSUE THREAD

**Issue by FabricioLopees** [mohitgedar/mp3-or-mp4-from-youtube#1]
### I'm using this extension on my Chrome, but it doesn't download automatically

<p>It redirects to the website so I can paste the link and download it. From what I undestand, this extension should automatically download as soon as I select one of the options (mp3 or mp4), right?</p>

<i><strong>OBS: I am working on this project to improve the file structure of this project. Soon I will be making a pull request for my version for you to evaluate and perhaps merge with the official project.</strong></i>

![Youtube Mp3 Converter Screenshot](https://github.com/mohitgedar/mp3-or-mp4-from-youtube/assets/162738847/8a287238-5906-459e-a82c-435a0a1596e7)

**Comment by mohitgedar** [comment]
I am not using any kind of API , I just automated the process of coping and pasting link and then downloading using this website , as I mentioned in my readme file that this extension don't work for first time , just keep the new website's tab open , go back to youtube and again click the extension and do nothing untill you get a option to download , and the concern that it don't download as soon as you click that is because I made it so , so that the default mp3 option works and also you get enough time  to select a option if you want.

**Comment by FabricioLopees** [comment]
I did this, but it didn't work. I kept the website tab open, went back to YouTube and selected the extension again and it takes me back to the website page.

**Comment by mohitgedar** [comment]
i checked it in chrome ,brave and edge(chromium based one), its working . if there is still some issue try downloading new code again and try again.

**Comment by FabricioLopees** [comment]
I use arch Linux and chrome, maybe there is some subtle change in the code from chrome to arch that caused this. I'll be trying with other browsers!

**Comment by mohitgedar** [comment]
sure. use new code , there are some changes in it .
